[build]
  base = "ui/"
  command = "rm -rf node_modules package-lock.json && npm ci && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://air-pollution-visualiser-191519804984.europe-west1.run.app"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=()"
