[build]
  base = "ui/"
  command = "npm install @rollup/rollup-linux-x64-gnu && npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://air-pollution-visualiser-191519804984.europe-west1.run.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=()"
